package com.example.genetiicz.Service;

import org.springframework.stereotype.Service;


//JWT SERVICE WILL HANDLE THE LOGIC OF THE JWT TOKEN. IT WILL GENERATE THE LOGIC BASED ON VALIDATION.
//THE UserService WILL HANDLE WHO THIS PERSON IS FROM THE DATABASE AND THEN THE JWT WILL GENERATE TOKEN, VALIDATE IT, EXTRACT AND CROSSCHECK
//AUTHREQUESTDTO IF TOKEN IS VALID == USER, AND IN THIS ASPECT THE USER IS ADMIN WHO IS ME.
@Service
public class JwtAuthService {
}
